channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - scikit-learn
  # additional frameworks
  - xgboost
  - catboost
  - lightgbm
  - faiss-cpu
  - scikit-learn-intelex
  - modin-all
  # sklbench dependencies
  - scikit-learn
  - pandas
  - tabulate
  - fastparquet
  - h5py
  - kaggle
  - openpyxl
  - tqdm
  - psutil
  - requests
  - py-cpuinfo
