channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  # additional frameworks
  - xgboost
  - catboost
  - lightgbm
  - faiss-cpu
  - modin-all
  - intel::scikit-learn-intelex
  - intel::daal4py
  - intel::dpctl
  - intel::dpnp
  # sklbench dependencies
  - scikit-learn=1.4.*
  - pandas
  - tabulate
  - fastparquet
  - h5py
  - kaggle
  - openpyxl
  - tqdm
  - psutil
  - requests
  - py-cpuinfo
